# Site settings
title: Can You DevOps With Windows? 
email: steven.murawski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My ramblings on PowerShell, DevOps, and Windows Server administration.
baseurl: "" # "powershell" # the subpath of your site, e.g. /blog/
url: "http://stevenmurawski.azurewebsites.net" # the base hostname & protocol for your site
twitter_username: stevenmurawski
github_username:  smurawski

permalink: /powershell/:year/:month/:title/index.html

# Build settings
markdown: redcarpet
markdown_ext: markdown, md

exclude: ['Gemfile', 'Gemfile.lock', 'appveyor.yml', 'LICENSE']
