environment:
  access_token:
    secure: kdTM19O71SwMJdvAMtH5MTow+ovQ3jtqIvDwPZkeS0t7rWZGv4vHjfCi1C22tfuk
  matrix:
    - ruby_version: "200"

clone_folder: c:\projects\blog
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

cache:
  - C:\Ruby200\lib\ruby\gems\2.0.0
  - C:\Ruby200\bin
  - C:\Ruby22\bin
  - C:\Ruby22\lib\ruby\gems\2.2.0

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem install bundler --quiet --no-ri --no-rdoc || gem install bundler --quiet --no-ri --no-rdoc || gem install bundler --quiet --no-ri --no-rdoc
  - gem --version
  - bundler --version

build_script:
  - ps: >-
      $d = get-date;
      dir _posts -file |
      where {$_.name -notmatch '^\d{4}-\d{2}'} | 
      foreach-object {$NewName = "{0:0000}-{1:00}-{2:00}-$($_.name)" -f $d.year, $d.month, $d.day; git mv "_posts/$($_.name)" "_posts/$NewName";}

  - bundle install || bundle install || bundle install
  - bundle exec jekyll build
  - cd _site
  - 7z a -tzip c:\projects\blog\deploy.zip .\
  - cd ..
  - appveyor PushArtifact deploy.zip -Type WebDeployPackage

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "steven.murawski@gmail.com"
  - git config --global user.name "Steven Murawski"
  - git remote add upstream "https://github.com/smurawski/blog.git"
  - git commit -m "[skip ci] - updated posts"
  - git push upstream master

deploy:
- provider: WebDeploy
  server: https://stevenmurawski.scm.azurewebsites.net:443/msdeploy.axd?site=stevenmurawski
  website: stevenmurawski
  username: $stevenmurawski
  password:
    secure: D7J8hUxui5QdUfZdV3KExmTDHJXzzrpz6kwMy0M9Ph4NIL1CinfnneEb4jN8e4XpOY3lA732m1cxsqYJp7F+Zw==
  remove_files: true
